"""Write public_notebooks.csv and important_discussions.csv into the workspace."""
import sys

import pandas as pd

WS = sys.argv[1]
K = "https://www.kaggle.com/code/"
nb = [
    dict(category="D. EDA/preprocessing (host starter)", notebook="kacchi_starter", author="Tasnim Mahfuz Nafis (host team; linked from Overview)",
         url=K + "tasnimmahfuznafis/kacchi-starter", last_run_utc="2026-10-06 12:15", votes=4, version="UNVERIFIED (API gives latest run only)",
         public_lb="UNVERIFIED", public_lb_status="No score claimed; RF submission score not on LB as a named entry", private_lb="N/A (competition running)",
         cv_score="UNVERIFIED (execution log empty)", cv_source="-", validation_method="single 75/25 train_test_split (random_state=42)",
         model="RandomForestClassifier(300) on raw columns; DecisionTree(max_depth=2) exercise left blank", backbone="-",
         preprocessing="Bangla->ASCII digits for fairy_lights; drop rows with missing aloo; x10 fix left as exercise",
         features="8 raw numeric + drone flag", feature_engineering="none (hints at per-guest ratio)", target_encoding="no", augmentation="no",
         loss="gini (RF)", optimizer="-", scheduler="-", hyperparameters="n_estimators=300, random_state=42", folds="1 holdout", seeds="42",
         external_data="no", pretrained_models="no", pseudo_labeling="no", ensembling="RF bagging only", blending="no", stacking="no", tta="no",
         post_processing="no", runtime="< 1 min CPU", reproducibility="High (code complete)", available_weights="no", available_code="yes",
         downloadable="yes (kaggle kernels pull)", potential_leakage="none", potential_public_lb_overfit="none (not tuned)",
         solution_family="F0 raw-feature tree models", test_prediction_vector="not published (no output file)",
         notes="Story-driven teaching notebook; contains the decisive hints: 'per guest', 'too little/too much aloo', 'big test weddings', 'tiny tree'."),
    dict(category="D. EDA/preprocessing", notebook="Kacchi Aloo Mystery Deep EDA", author="FOYSAL (foysalemonshanto; public LB rank 1 team)",
         url=K + "foysalemonshanto/kacchi-aloo-mystery-deep-eda", last_run_utc="2026-10-06 16:01", votes=0, version="UNVERIFIED",
         public_lb="UNVERIFIED", public_lb_status="Writes submission_rule.csv (no score claimed)", private_lb="N/A",
         cv_score="Fitted band 0.9549 ± 0.0070; LGBM apg-only 0.9536 ± 0.0024; fixed (1,2) 0.9446 ± 0.0201; LR apg+apg² 0.9420; LGBM engineered 0.9407; LR engineered 0.9317; LGBM raw 0.8596; LR raw 0.5554",
         cv_source="VERIFIED from Kaggle execution log (not independently re-run: data gated)", validation_method="StratifiedKFold(5, shuffle, rs=0) on 776 clean rows",
         model="accuracy-optimal two-threshold band on aloo/guest (grid 0.005); also soft-band MLE, LR, LGBM for comparison", backbone="-",
         preprocessing="read as str; Bangla digits->ASCII; x10 fix (apg>3 -> /10); drop 24 missing-aloo rows",
         features="aloo_pg (+ mutton/borhani/fairy per guest for comparison)", feature_engineering="per-guest ratios", target_encoding="no", augmentation="no",
         loss="0-1 accuracy (grid search); NLL for soft-band MLE", optimizer="grid search / Nelder-Mead", scheduler="-",
         hyperparameters="lo grid 0.85-1.15, hi grid 1.85-2.25, step 0.005", folds="5", seeds="0", external_data="no", pretrained_models="no",
         pseudo_labeling="no", ensembling="no", blending="no", stacking="no", tta="no", post_processing="band thresholds (0.970, 2.010)",
         runtime="~1 min CPU", reproducibility="High", available_weights="-", available_code="yes", downloadable="yes",
         potential_leakage="none found (test-only features not used)", potential_public_lb_overfit="Low (no LB tuning visible); thresholds fitted to train noise (see analysis)",
         solution_family="F1 accuracy-optimal ratio band", test_prediction_vector="V0 (identical to K006 band_rule)",
         notes="Claims ~95-96% ceiling, error = label noise at soft edges; finds no event/city/drone effect."),
    dict(category="B/C. Claimed LB score + strong CV notebook", notebook="LB_0.95027_Kacchi Aloo Theory", author="FOYSAL (foysalemonshanto)",
         url=K + "foysalemonshanto/lb-0-95027-kacchi-aloo-theory", last_run_utc="2026-10-06 15:55", votes=0, version="UNVERIFIED",
         public_lb="0.95027 (title claim)", public_lb_status="PARTICIPANT CLAIM - UNVERIFIED (equals host benchmark 172/181; could not be confirmed without submitting)",
         private_lb="N/A", cv_score="band_rule 0.9558 (se 0.0018); lgbm_logapg 0.9541; knn5 0.9513; fixed_1_2 0.9446; logmle_band 0.9407",
         cv_source="VERIFIED from Kaggle execution log", validation_method="RepeatedStratifiedKFold(5 x 10, rs=42)",
         model="band rule (accuracy-optimal, plateau centre); LGBM on log apg; kNN5 on log apg; log-space soft-band MLE", backbone="-",
         preprocessing="same as Deep EDA", features="apg / log apg only", feature_engineering="ratio + log", target_encoding="no", augmentation="no",
         loss="0-1 / binary logloss / NLL", optimizer="grid / GBDT / Nelder-Mead", scheduler="-",
         hyperparameters="grid step 0.0025; LGBM n=300 lr=0.02 leaves=4 mcs=15 subsample=0.8", folds="5x10", seeds="LGBM 10 seeds",
         external_data="no", pretrained_models="no", pseudo_labeling="no", ensembling="seed averaging (LGBM)", blending="no", stacking="no", tta="no",
         post_processing="threshold band (0.9700, 2.0087)", runtime="~2-3 min CPU", reproducibility="High", available_weights="-", available_code="yes",
         downloadable="yes (5 submission CSVs)", potential_leakage="none", potential_public_lb_overfit="Title advertises LB; author's team has 10 submissions and best public 0.96685, i.e. 3 rows above this file (selection on 181 rows)",
         solution_family="F1 accuracy-optimal ratio band (+ F2 smooth ratio models as alternates)",
         test_prediction_vector="submission.csv = band_rule = V0; lgbm_logapg = V2; knn5 = V1; logmle_band = V3",
         notes="Best-documented public pipeline; selects final by CV (good practice)."),
    dict(category="C. Strong CV/training notebook (+ Best Aloo Theory entry)", notebook="The Aloo Theory: The Goldilocks Band", author="Rafiur Rahman (rafiurrahman01; public 0.95580)",
         url=K + "rafiurrahman01/the-aloo-theory-the-goldilocks-band", last_run_utc="2026-10-07 06:59", votes=0, version="UNVERIFIED",
         public_lb="Team best 0.95580 (VERIFIED on LB)", public_lb_status="Which of the author's 3 submissions produced 0.95580 is UNVERIFIED",
         private_lb="N/A", cv_score="band rule 0.9558 ± 0.0147; fixed 1-2 rule 0.9446 ± 0.0207; LightGBM all features 0.9386 ± 0.0176",
         cv_source="VERIFIED from Kaggle execution log", validation_method="StratifiedKFold(5) x 3 shuffles (seeds 0-2)",
         model="midpoint-cut band rule (lo fitted below 1.5, hi above 1.5)", backbone="-",
         preprocessing="unicode-safe digit translation for all numeric cols; x10 fix; drop missing aloo", features="aloo_per_guest",
         feature_engineering="ratios; log-log logit falsification tests; alternative denominators", target_encoding="no", augmentation="no",
         loss="0-1", optimizer="exhaustive cut search", scheduler="-", hyperparameters="cuts = median of argmax plateau", folds="5x3", seeds="0,1,2",
         external_data="no", pretrained_models="no", pseudo_labeling="no", ensembling="no", blending="no", stacking="no", tta="no",
         post_processing="closed band [0.971, 2.010]", runtime="< 1 min CPU", reproducibility="High", available_weights="-", available_code="yes",
         downloadable="yes", potential_leakage="none", potential_public_lb_overfit="Low",
         solution_family="F1 ratio band (midpoint variant)", test_prediction_vector="V2 (identical to K006 lgbm_logapg; differs from V0 on W0968, W1163)",
         notes="Strongest 'why' narrative so far: ratio test, mutton theory rejected (p=0.22-0.34), extra-eater denominators rejected."),
]
pd.DataFrame(nb).to_csv(f"{WS}/public_notebooks.csv", index=False, encoding="utf-8")

disc = [dict(title="(no discussion topics exist)", author="-", link="https://www.kaggle.com/competitions/the-great-kacchi-aloo-mystery/discussion",
             date="checked 2026-10-07 ~09:00 UTC", participant_or_organizer="-", lb_rank="-",
             key_claim="Kaggle API competition_list_topics returned total_count = 0", experiment_result="-", reliability="VERIFIED (API)",
             practical_implication="No organizer clarifications exist beyond the Overview/Data/Rules pages; treat the Data-page field notes as the only host guidance. Re-check before the deadline."),
        dict(title="Data page: 'Field Notes from Mitu (read this!)'", author="BdAIO (host)", link="https://www.kaggle.com/competitions/the-great-kacchi-aloo-mystery/data",
             date="2026-10-06", participant_or_organizer="Organizer (official page, not a forum post)", lb_rank="-",
             key_claim="Empty aloo_count boxes; Bangla digits in fairy_lights; possible extra zero in potato counts; some test weddings much bigger than train; data is synthetic",
             experiment_result="Public audits: 24 missing / 15 Bangla / 6 x10 in train, none in test; 145 test weddings > 700 guests", reliability="OFFICIAL FACT",
             practical_implication="Clean train only; use scale-free ratio features; validate with a size-stress fold."),
        dict(title="Overview: 'The fanciest model doesn't always win. Thinking does.'", author="BdAIO (host)", link="https://www.kaggle.com/competitions/the-great-kacchi-aloo-mystery/overview",
             date="2026-10-06", participant_or_organizer="Organizer", lb_rank="-", key_claim="Hint that a simple engineered rule beats complex models; separate 'Best Aloo Theory' notebook prize",
             experiment_result="Confirmed by public CV: band rule 0.955 vs LGBM raw 0.86", reliability="OFFICIAL FACT",
             practical_implication="Compete on the explanation prize too; do not invest in heavy models."),
        dict(title="Rules page: World AI Week + contact bdaio@bdosn.org", author="BdAIO (host)", link="https://www.kaggle.com/competitions/the-great-kacchi-aloo-mystery/rules",
             date="2026-10-06", participant_or_organizer="Organizer", lb_rank="-", key_claim="Educational competition for high-school students; help via email",
             experiment_result="-", reliability="OFFICIAL FACT", practical_implication="Email the host for clarifications (e.g. number of final selections, prize judging criteria) - answers are not public."),
        ]
pd.DataFrame(disc).to_csv(f"{WS}/important_discussions.csv", index=False, encoding="utf-8")
print("written")
