"""Make the explanation reproducible and distinguish observations from stories."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[2]


def main():
    p=ROOT/'solution/best_aloo_theory.ipynb'
    nb=json.loads(p.read_text())
    nb['cells'][0]['source']='''# The Aloo Theory: count potatoes per guest

**Mitu's question:** which weddings are likely to have guests return for seconds?

The strongest simple pattern we found is **potatoes divided by guests**. In this synthetic dataset, weddings with roughly **0.97 to 2.01 potatoes per guest** usually have label 1. Weddings below or above that band usually have label 0.

For example, 150 potatoes for 100 guests and 1,500 potatoes for 1,000 guests both give **1.5 potatoes per guest**, so the same rule predicts seconds for both. A bigger potato count alone tells us little without knowing how many guests share it.

The notebook checks this idea on held-out training weddings, compares it with other ideas, and shows where it makes mistakes. The tested models achieve about **95–96% cross-validation accuracy**. That is an observed result, **not a proven accuracy ceiling**.

The food story is a useful way to remember the pattern: too few potatoes may disappoint people; too many may change the balance of a plate. **The dataset does not prove either explanation causes real guests to return.** The competition data was generated by a computer, not collected at real weddings.

**বাংলায়:** শুধু আলুর সংখ্যা নয়—অতিথিপ্রতি আলু গুনুন। প্রায় ১ থেকে ২টি আলু হলে এই কৃত্রিম ডেটায় দ্বিতীয় প্লেট নেওয়ার সম্ভাবনা বেশি। কেন এমন হয়, সেই গল্প আর ডেটায় পাওয়া প্রমাণ এক বিষয় নয়।

Run all cells to reproduce the analysis. The rule and validation below use training labels; no leaderboard-derived test labels enter these fits.
'''.splitlines(True)
    replacements={
        'about 95% is the ceiling':'about 95% was achieved by the tested rule',
        '## 8. How good can anyone get?':'## 8. What does validation tell us, and what is only a simulation?',
        'Nobody':'The tested models',
    }
    for i,cell in enumerate(nb['cells']):
        s=''.join(cell['source'])
        if cell['cell_type']=='markdown':
            for old,new in replacements.items(): s=s.replace(old,new)
            if i==9:
                s=s.replace("Babul Baburchi's mutton theory doesn't hold up.","This fit gives little evidence for a separate mutton effect.")
            if s.startswith('**What this shows:** each theory'):
                s='''**What this shows:** the listed features are allowed to move each edge within a specified grid. Validation does not show a clear improvement over the ratio rule. This is evidence about these tested models, not proof that every possible model or interaction would fail. Unexplained errors should not automatically be called irreducible randomness.'''
            if s.startswith('**What this shows:** right at each edge'):
                s=s.replace('A smooth, blurry edge would almost never produce runs like these.', 'These observations motivate a sharp rule. Finite runs of labels do not prove the hidden generator has an exactly sharp boundary; the next section compares models on held-out rows.')
            if s.startswith('**What this shows:** the best honest rule'):
                s='''**What this shows:** cross-validation puts the tested sharp rule around 95–96%. The figures here also simulate test outcomes using its out-of-fold error rates and an assumed random 181/219 public/private split. Those probabilities depend on the simulation assumptions; they are not guarantees about final rank or evidence of a universal ceiling. Correlated errors or a different hidden generator could change them.'''
            if s.startswith('## 🥔 The Aloo Theory (final answer)'):
                s='''## The Aloo Theory, in plain words

> **Divide potatoes by guests. In this synthetic dataset, the middle band usually predicts a second plate.**

The approximate training-fitted limits are **0.97 and 2.01 potatoes per guest**. This explains why the ratio transfers to larger weddings better than a rule on raw potato counts. The rule still makes mistakes, especially near its boundaries. We did not find a reliable improvement from the other features in the models tested here.

This is a useful predictive explanation of this dataset. The story about sharing and the balance of a plate is an interpretation, not a proven cause. We do not know the generator's source code or the true maximum achievable accuracy.

**Public-score disclosure (9 October 2026):** our later OPT01 submission scored **0.99447** after automated leaderboard experiments. It differs from Q01 on five inferred public rows. That score is not the cross-validation accuracy of this theory, and it gives no additional improvement on private rows. The notebook's model and validation results above remain training-based.

**Source:** Tasnim Mahfuz Nafis, *The Great Kacchi Aloo Mystery*, Kaggle, 2026. [Competition overview](https://www.kaggle.com/competitions/the-great-kacchi-aloo-mystery). The data is synthetic and is not a guide for planning a real wedding.
'''
            cell['source']=s.splitlines(True)
        else:
            if '"smooth (soft) band, max-likelihood"' in s:
                old='(lambda th: ((v.apg > th[0]) & (v.apg < th[1])).astype(int))(soft_band_fit(t.apg.values, t.y.values))'
                new='(lambda th: (expit(th[2] * (np.log(v.apg) - np.log(th[0]))) * expit(th[2] * (np.log(th[1]) - np.log(v.apg))) >= 0.5).astype(int))(soft_band_fit(t.apg.values, t.y.values))'
                assert old in s
                s=s.replace(old,new)
            s=s.replace('"expected accuracy on these 400 test weddings"','"simulated expected test accuracy under ring-error assumptions"')
            s=s.replace('"test weddings within 0.1 of an edge (where luck lives)"','"test weddings within 0.1 of an edge"')
            cell['source']=s.splitlines(True);cell['outputs']=[];cell['execution_count']=None
            cell['metadata'].pop('execution',None)
    nb['metadata'].pop('widgets',None)
    p.write_text(json.dumps(nb,indent=1,ensure_ascii=False)+'\n')
    kernel=ROOT/'solution/kaggle_theory_kernel'
    (kernel/'aloo-theory.ipynb').write_text(json.dumps(nb,indent=1,ensure_ascii=False)+'\n')
    meta=json.loads((kernel/'kernel-metadata.json').read_text())
    meta.update(title='The Aloo Theory: Count Potatoes per Guest',is_private=True)
    (kernel/'kernel-metadata.json').write_text(json.dumps(meta,indent=2)+'\n')
    print('Updated theory notebook and private Kaggle source')


if __name__=='__main__':main()
